### ISSUE TITLE
IRI Owner copy/paste

### ISSUE THREAD

**Issue by rwalkerands** [AGLDWG/iri-registry-ont#1]
Copy/paste error in IRIOwner's label:
```
irg:IRIOwner rdfs:label "IRI Submmitter" .
```

&#8594;

```
irg:IRIOwner rdfs:label "IRI Owner" .
```

**Comment by nicholascar** [comment]
Fixed by Commit https://github.com/AGLDWG/iri-registry-ont/commit/496016494745fabe0eea8a0e4fef76e96a1a6886
