### ISSUE TITLE
Clarify use of versioning/time intervals for status

### ISSUE THREAD

**Issue by rwalkerands** [AGLDWG/iri-registry-ont#2]
In the original ontology, `reg:RegisterItem` is a subclass of `version:VersionedThing`, so that each registry item already has the possibility of being versioned "in full", with each instance having an associated `version:Version`&#8594;`time:Interval`. (See Overview diagram at http://epimorphics.com/public/vocabulary/Registry.html. Hmm, `reg:Register` is also a subclass of `version:VersionedThing`.)

So, it would be good to have at least a clarification of how the additional versioning of the status property is intended to be used and/or how it "adds value".

**Comment by nicholascar** [comment]
Fixed by Commit https://github.com/AGLDWG/iri-registry-ont/commit/3983a1b0595178aac242f14e7507fb43b3cd8375

**Comment by nicholascar** [comment]
Accidental closing: it was Issue 3 that should have been closed.

**Comment by nicholascar** [comment]
> In the original ontology, `reg:RegisterItem` is a subclass of `version:VersionedThing`

This is so the registered item could be versioned for any reason - status change perhaps but also content, title ownership etc. change. 

I originally thought this was overkill for sequencing status changes (to check that a fixed state change model was followed) and that having a separate timeline for status would be easier to use. This will be true for data access like SPARQL queries (i.e. if the statuses are neatly in their own set of temporal things, not whole registered item versions, they will be easy to select out) but I think that implementation in Drupal will be much harder.

Drupal's custom content types do versioning like `version:VersionedThing` and to cater for statuses with `StatusPeriod` objects, we would have to relate m:n `version:VersionedThing`:`StatusPeriod`  which sounds nasty.

So, on reflection (thanks for the prompt Richard) I will update the IRI Reg Ont to drop `StatusPeriod` and to just fall back on whole-of-registered item versioning.

**Comment by nicholascar** [comment]
Addresses in Commit https://github.com/AGLDWG/iri-registry-ont/commit/1b18adb027ea9497bac5eae985aab0f155520bcb as described above
