### ISSUE TITLE
hasStatus definition

### ISSUE THREAD

**Issue by rwalkerands** [AGLDWG/iri-registry-ont#3]
Typos in definition of `irg:hasStatus`:

1. ```irg:hasStatus rdfs:comment """... reg:statusb ..."""@en .```
&#8594;
```irg:hasStatus rdfs:comment """... reg:status ..."""@en .```

2. ```irg:hasStatus rdfs:domain time:ProperInterval .```
&#8594;
```irg:hasStatus rdfs:domain irg:StatusPeriod .```

**Comment by nicholascar** [comment]
Fixed by Commit https://github.com/AGLDWG/iri-registry-ont/commit/3983a1b0595178aac242f14e7507fb43b3cd8375
